spring.application.name=sap_springboot_test

# SAP JCo demo config.
# Fill these values with your SAP account and server information before testing.
# This demo uses standard RFC: STFC_CONNECTION
sap.jco.destination-name=Kfp-DEV
sap.jco.ashost=192.168.6.51
sap.jco.sysnr=00
sap.jco.client=301
sap.jco.user=USER01
sap.jco.passwd=12345678
sap.jco.lang=ZH
sap.jco.saprouter=
sap.jco.pool-capacity=3
sap.jco.peak-limit=10
